// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/s2.proto

package s2

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Park service

type ParkService interface {
	Get(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type parkService struct {
	c    client.Client
	name string
}

func NewParkService(name string, c client.Client) ParkService {
	return &parkService{
		c:    c,
		name: name,
	}
}

func (c *parkService) Get(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Park.Get", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Park service

type ParkHandler interface {
	Get(context.Context, *Request, *Response) error
}

func RegisterParkHandler(s server.Server, hdlr ParkHandler, opts ...server.HandlerOption) error {
	type park interface {
		Get(ctx context.Context, in *Request, out *Response) error
	}
	type Park struct {
		park
	}
	h := &parkHandler{hdlr}
	return s.Handle(s.NewHandler(&Park{h}, opts...))
}

type parkHandler struct {
	ParkHandler
}

func (h *parkHandler) Get(ctx context.Context, in *Request, out *Response) error {
	return h.ParkHandler.Get(ctx, in, out)
}
